Source/Presentation/Management.EndPoint.MVCApp/Controllers/AccountIdentityController.cs
using Domain.Concrete.Schema.HR;
using Main.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;


namespace BootCampManagement.EndPoint.MVCApp.Controllers
{

    public class AccountIdentityController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public IEnumerable<IdentityUser> Users { get; private set; } = Enumerable.Empty<IdentityUser>();
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountIdentityController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

        }

        [Authorize(Roles = "Admin")]
        public IActionResult UserList()
        {
            Users = _userManager.Users.ToList();
            return View(Users);
        }
        //-------------------------------------------------------------//
        public string ID { get; set; }

        [BindProperty]
        [Unicode]
        public string? UserName { get; set; }

        [BindProperty]
        public string? Password { get; set; }

        [BindProperty]
        [EmailAddress]
        [Unicode]
        public string? Email { get; set; }



        public async Task<IActionResult> CreateUser()
        {

            if (ModelState.IsValid)
            {
                //if (string.IsNullOrEmpty(Password))
                //{
                //    ModelState.AddModelError("Password", "Password is required.");
                //    return View();
                //}


                IdentityUser user = new()
                {
                    UserName = UserName,
                    Email = Email,
                };

                try
                {

                    IdentityResult result = await _userManager.CreateAsync(user, Password);


                    if (result.Succeeded)
                    {
                        return RedirectToAction("UserList");
                    }
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Password", "Password is required.");
                }
            }

            return View();
        }
        //-------------------------------------------------------------//
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UserEdit(string id)
        {
            async Task UserInfo()
            {
                var user = await _userManager.FindByIdAsync(id);
                UserName = user.UserName;
                Email = user.Email;

            }


            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(id);

                user.UserName = UserName;
                user.Email = Email;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded && !string.IsNullOrEmpty(Password))
                {
                    await _userManager.RemovePasswordAsync(user);
                    result = await _userManager.AddPasswordAsync(user, Password);
                }
                if (result.Succeeded)
                {
                    return RedirectToAction("UserList");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View();
        }

        //-------------------------------------------------------------//
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("UserList");

        }



        //-------------------------------------------------------------//
        [BindProperty]
        public List<string> Roles { get; set; }
        [BindProperty]
        public IdentityUser CurentUser { get; set; }
        public List<IdentityRole> AllRoles { get; set; }
        public List<string> UserRoles { get; set; }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ManageUserRole(string id)
        {

            CurentUser = await _userManager.FindByIdAsync(id);

            //if (CurentUser == null)
            //{
            //    // Handle the case where the user is not found.
            //    return NotFound();
            //}

            UserRoles = (await _userManager.GetRolesAsync(CurentUser)).ToList();
            AllRoles = _roleManager.Roles.ToList();
            ViewBag.Roles = CurentUser;
            ViewBag.ID = id;
            ViewBag.AllRoles = AllRoles;
            var roleInfo = new 
            {
                Roles = UserRoles,
                ID = id,
                UserName = CurentUser,
                AllRole = AllRoles
            };

            return View(roleInfo);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> PostUserRole(string id)
        {
            CurentUser = await _userManager.FindByIdAsync(id);
            AllRoles = _roleManager.Roles.ToList();

            foreach (var item in AllRoles)
            {
                if (Roles.Contains(item.Name))
                {
                    if (!(await _userManager.IsInRoleAsync(CurentUser, item.Name)))
                    {
                        await _userManager.AddToRoleAsync(CurentUser, item.Name);
                    }
                }
                else
                {
                    if (await _userManager.IsInRoleAsync(CurentUser, item.Name))
                    {
                        await _userManager.RemoveFromRoleAsync(CurentUser, item.Name);
                    }
                }
            }
            return RedirectToAction("UserList");

        }


    }





    
}

Source/Presentation/Management.EndPoint.MVCApp/Controllers/CategoryController.cs
using Application.Schema.HR;
using Domain.Concrete.Schema.HR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NHibernate.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace BootCampManagement.EndPoint.MVCApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly CategoryRepository _categoryRepository;
        private readonly NHibernate.ISession _session;
        public CategoryController(NHibernate.ISession session, CategoryRepository categoryRepository)
        {
            _session = session;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {

            //var categories = _categoryRepository.Categories.ToList();
            //return Json(categories);
            var categories = _categoryRepository.Categories.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };
            return Json(categories, jsonOptions);
        }
        public IActionResult CategoryList()
        {
            //var categories = _categoryRepository.Categories.ToList();
            //return Json(categories);
            var categories = _categoryRepository.Categories.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };
            var model = _session.Query<Category>().OrderBy(x => x.ParentID).ToList();

            return View(model);
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                _categoryRepository.BeginTransaction();

                var FA = await _categoryRepository.Categories.FirstOrDefaultAsync(x => x.ID == id);

                if (FA == null)
                    return BadRequest("چنین ایتمی وجود ندارد.");

                await _categoryRepository.Delete(FA);
                await _categoryRepository.Commit();

                return Json(new { success = true, message = " با موفقیت حذف شد." });
            }
            catch (Exception ex)
            {
                await _categoryRepository.Rollback();
                return Json(new { success = false, message = $"خطا در حذف : {ex.Message}" });
            }
            finally
            {
                _categoryRepository.CloseTransaction();
            }

        }
        private async Task SaveAsync(Category cat)
        {
            await _session.SaveOrUpdateAsync(cat);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] Category cat)
        {


            try
            {
                await SaveAsync(cat);

                return Ok(new { Message = "اطلاعات با موفقیت ذخیره شد." });
            }
            catch (Exception ex)
            {
                return BadRequest(new { Message = $"خطا در ذخیره اطلاعات: {ex.Message}" });
            }
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
    }
}

Source/Presentation/Management.EndPoint.MVCApp/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Domain.Concrete.Schema.HR;

[Authorize(Roles = "Admin")]

public class RoleController : Controller
{
    private readonly RoleManager<IdentityRole> _roleManager;

    public RoleController(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public IActionResult List()
    {
        var roles = _roleManager.Roles.ToList();
        return View(roles);
    }

    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(CreateRoleViewModel model)
    {
        if (ModelState.IsValid)
        {
            var identityRole = new IdentityRole(model.Name);
            var result = await _roleManager.CreateAsync(identityRole);
            if (result.Succeeded)
            {
                return RedirectToAction("List");
            }
            foreach (var item in result.Errors)
            {
                ModelState.AddModelError("", item.Description);
            }
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(string Name)
    {
        var role = await _roleManager.FindByNameAsync(Name);
        if (role != null)
        {
            var result =
                 await _roleManager.DeleteAsync(role);
            //if(!result.Succeeded)
            //{
            //    foreach (var item in result.Errors)
            //    {
            //        ModelState.AddModelError("", item.Description);
            //    }
            //}
        }

        return RedirectToAction("List");
    }


    public async Task<IActionResult> Edit(string id)
    {
        var role = await _roleManager.FindByIdAsync(id);
        var editRoleViewModel = new EditRoleViewModel
        {
            Id = role.Id,
            Name = role.Name
        };
        return View(editRoleViewModel);
    }
    [HttpPost]
    public async Task<IActionResult> Edit(IdentityRole model , string id)
    {
        if (ModelState.IsValid)
        {
            var identityRole = await _roleManager.FindByIdAsync(model.Id);
            if (identityRole != null)
            {
                identityRole.Name = model.Name;
                var result = await _roleManager.UpdateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("List");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
        }

        return View(model);
    }
}

Source/Presentation/Management.EndPoint.MVCApp/Controllers/TransactionController.cs
using Application.Schema.HR;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using System.Text.Json;
using NHibernate.Linq;
using Domain.Concrete.Schema.HR;
using Microsoft.AspNetCore.Authorization;

namespace BootCampManagement.EndPoint.MVCApp.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly TransactionRepository _transactionRepository;
        private readonly NHibernate.ISession _session;
        public TransactionController(NHibernate.ISession session, TransactionRepository transactionRepository)
        {
            _session = session;
            _transactionRepository = transactionRepository;
        }

        public IActionResult Index()
        {
            //var transactions = _transactionRepository.Transactions.ToList();
            //return Json(transactions);
            var categories = _transactionRepository.Transactions.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };

            return Json(categories, jsonOptions);
        }
        public IActionResult TransactionList()
        {
            //var transactions = _transactionRepository.Transactions.ToList();
            //return Json(transactions);
            var categories = _transactionRepository.Transactions.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };

            return View(categories);
        }



        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                _transactionRepository.BeginTransaction();
                var FA = await _transactionRepository.Transactions.FirstOrDefaultAsync(x => x.ID == id);
                if (FA == null)
                    return BadRequest("چنین شخصی وجود ندارد.");

                await _transactionRepository.Delete(FA);
                await _transactionRepository.Commit();
                return Json(new { success = true, message = "شخص با موفقیت حذف شد." });
            }
            catch (Exception ex)
            {
                await _transactionRepository.Rollback();
                return Json(new { success = false, message = $"خطا در حذف شخص: {ex.Message}" });
            }
            finally
            {
                _transactionRepository.CloseTransaction();
            }
        }
        private async Task SaveAsync(myTransaction Tra)
        {
            await _session.SaveOrUpdateAsync(Tra);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] myTransaction Tra)
        {


            try
            {
                await SaveAsync(Tra);

                return Ok(new { Message = "اطلاعات با موفقیت ذخیره شد." });
            }
            catch (Exception ex)
            {
                return BadRequest(new { Message = $"خطا در ذخیره اطلاعات: {ex.Message}" });
            }
        }
        public IActionResult CreateTransaction()
        {
            return View();
        }

    }
}

Source/Presentation/Management.EndPoint.MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Main</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Main.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header class="d-flex align-items-center justify-content-center">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccountIdentity" asp-action="CreateUser">ثبت یوزر جدید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccountIdentity" asp-action="UserList">مشاهده لیست یوزر</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FinancialAccount" asp-action="FinancialAccountList"> مشاهده حساب ها</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FinancialAccount" asp-action="CreateFinancialAccount"> ثبب حساب جدید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionType" asp-action="TransactionTypeList">مشاهده تایب های تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionType" asp-action="CreateType">ایجاد تایب های تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CategoryList">مشاهده کتگوری تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CreateCategory">ایجاد کتگوری تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionType_Category" asp-action="TransactionType_CategoryList">مشاهده تایپ-گتگوری تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionType_Category" asp-action="CreateTransactionTypeCategory">ایجاد تایپ-گتگوری تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="TransactionList">مشاهده تراکنش</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="CreateTransaction">ایجاد تراکنش</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="List">لیست رول</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Create">ایجاد رول</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthenticationIdentity" asp-action="Logout">LogOut</a>
                            </li>

                        }
                        else
                        {
                            


                        }
                       
                         
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>