Source/Presentation/Management.EndPoint.MVCApp/Controllers/TransactionType_CategoryController.cs
using Application.Schema.HR;
using Domain.Concrete.Schema.HR;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using System.Text.Json;
using NHibernate.Linq;
using Microsoft.AspNetCore.Authorization;

namespace BootCampManagement.EndPoint.MVCApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TransactionType_CategoryController : Controller
    {
        private readonly TransactionTypeCategoryRepository _transactionTypeCategoryRepository;
        private readonly NHibernate.ISession _session;
        public TransactionType_CategoryController(NHibernate.ISession session, TransactionTypeCategoryRepository transactionTypeCategoryRepository)
        {
            _session = session;
            _transactionTypeCategoryRepository = transactionTypeCategoryRepository;
        }

        public IActionResult Index()
        {

            //var transactionTypeCategories = _transactionTypeCategoryRepository.TransactionTypeCategories.ToList();
            //return Json(transactionTypeCategories);
            var categories = _transactionTypeCategoryRepository.TransactionTypeCategories.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };
            return Json(categories, jsonOptions);
        }
        public IActionResult TransactionType_CategoryList()
        {

            //var transactionTypeCategories = _transactionTypeCategoryRepository.TransactionTypeCategories.ToList();
            //return Json(transactionTypeCategories);
            var categories = _transactionTypeCategoryRepository.TransactionTypeCategories.ToList();
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve,
            };
            return View(categories);
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                _transactionTypeCategoryRepository.BeginTransaction();

                var FA = await _transactionTypeCategoryRepository.TransactionTypeCategories.FirstOrDefaultAsync(x => x.ID == id);

                if (FA == null)
                    return BadRequest("چنین چیزی وجود ندارد.");

                await _transactionTypeCategoryRepository.Delete(FA);
                await _transactionTypeCategoryRepository.Commit();

                return Json(new { success = true, message = " با موفقیت حذف شد." });
            }
            catch (Exception ex)
            {
                await _transactionTypeCategoryRepository.Rollback();
                return Json(new { success = false, message = $"خطا در حذف : {ex.Message}" });
            }
            finally
            {
                _transactionTypeCategoryRepository.CloseTransaction();
            }
        }
        private async Task SaveAsync(TransactionType_Category ttc)
        {
            await _session.SaveOrUpdateAsync(ttc);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] TransactionType_Category ttc)
        {
            try
            {
                await SaveAsync(ttc);

                return Ok(new { Message = "اطلاعات با موفقیت ذخیره شد." });
            }
            catch (Exception ex)
            {
                return BadRequest(new { Message = $"خطا در ذخیره اطلاعات: {ex.Message}" });
            }
        }
        public IActionResult CreateTransactionTypeCategory()
        {
            return View();
        }
    }
}

Source/Presentation/Management.EndPoint.MVCApp/Views/TransactionType_Category/CreateTransactionTypeCategory.cshtml
@model Domain.Concrete.Schema.HR.TransactionType_Category

@{
    ViewData["Title"] = "Create TransactionType_Category";
}
<h2>Create TransactionType_Category</h2>

<form method="post" asp-controller="TransactionType_Category" asp-action="Create" onsubmit="submitForm(); return false;">
   

    <div class="form-group">
        <label asp-for="CategoryID">CategoryID : </label>
        <input type="number" asp-for="CategoryID" class="form-control" />
        <span asp-validation-for="CategoryID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TransactionTypeCode">TransactionTypeCode: </label>
        <input type="number" asp-for="TransactionTypeCode" class="form-control" />
        <span asp-validation-for="TransactionTypeCode" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-5">Save</button>
</form>


<script>
    function submitForm() {
        const form = document.querySelector('form');
        const formData = new FormData(form);
        const jsonData = JSON.stringify(Object.fromEntries(formData));

        fetch('/TransactionType_Category/Create', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: jsonData
        })
            .then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Network response was not ok.');
                    alert('.شکست عملیات . مقادیر را بررسی کنید')

                }
            })
            .then(data => {
                alert('اطلاعات با موفقیت ثبت شد');
                window.location.href = '/TransactionType_Category/CreateTransactionTypeCategory'
            })
            .catch(error => {
                console.error('Error:', error);
                alert('.شکست عملیات . مقادیر را بررسی کنید')

            });
    }
</script>

Source/Presentation/Management.EndPoint.MVCApp/Views/TransactionType_Category/TransactionType_CategoryList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex align-items-start justify-content-center" style="height: 50vh">
    <table class="table" style="width: 1000px " dir="rtl">
        <thead>
            <tr>
                <td scope="col">ID</td>
                <th scope="col">CategoryID</th>
                <th scope="col">TransactionTypeCode</th>
                

            </tr>
        </thead>
        <tbody>

            @foreach (var FA in Model)
            {

                <tr>
                    <td>@FA.ID</td>
                    <td>@FA.CategoryID</td>
                    <td>@FA.TransactionTypeCode</td>
                   

                    <td>
                        <button type="button" asp-page="" class="btn btn-danger" onclick="deleteGender(@FA.ID) ">حذف</button>
                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>

<<script>
     function deleteGender(code) {
         if (confirm("آیا از حذف این  مطمئن هستید؟")) {
             fetch(`/TransactionType_Category/Delete/${code}`, {
                 method: 'DELETE',
                 headers: {
                     'Content-Type': 'application/json',
                 },
             })
                 .then(response => response.json())
                 .then(data => {
                     if (data.success) {
                         alert('حذف موفق');
                         location.reload();
                     } else {
                         alert('شکست در حذف');
                     }
                 })
                 .catch((error) => {
                     console.error('Error:', error);
                 });
         }
     }
</script>