Source/Presentation/Management.EndPoint.MVCApp/Controllers/AccountIdentityController.cs
using Domain.Concrete.Schema.HR;
using Main.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;


namespace BootCampManagement.EndPoint.MVCApp.Controllers
{

    public class AccountIdentityController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public IEnumerable<IdentityUser> Users { get; private set; } = Enumerable.Empty<IdentityUser>();
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountIdentityController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

        }

        [Authorize(Roles = "Admin")]
        public IActionResult UserList()
        {
            Users = _userManager.Users.ToList();
            return View(Users);
        }
        //-------------------------------------------------------------//
        public string ID { get; set; }

        [BindProperty]
        [Unicode]
        public string? UserName { get; set; }

        [BindProperty]
        public string? Password { get; set; }

        [BindProperty]
        [EmailAddress]
        [Unicode]
        public string? Email { get; set; }



        public async Task<IActionResult> CreateUser()
        {

            if (ModelState.IsValid)
            {
                //if (string.IsNullOrEmpty(Password))
                //{
                //    ModelState.AddModelError("Password", "Password is required.");
                //    return View();
                //}


                IdentityUser user = new()
                {
                    UserName = UserName,
                    Email = Email,
                };

                try
                {

                    IdentityResult result = await _userManager.CreateAsync(user, Password);


                    if (result.Succeeded)
                    {
                        return RedirectToAction("UserList");
                    }
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Password", "Password is required.");
                }
            }

            return View();
        }
        //-------------------------------------------------------------//
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UserEdit(string id)
        {
            async Task UserInfo()
            {
                var user = await _userManager.FindByIdAsync(id);
                UserName = user.UserName;
                Email = user.Email;

            }


            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(id);

                user.UserName = UserName;
                user.Email = Email;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded && !string.IsNullOrEmpty(Password))
                {
                    await _userManager.RemovePasswordAsync(user);
                    result = await _userManager.AddPasswordAsync(user, Password);
                }
                if (result.Succeeded)
                {
                    return RedirectToAction("UserList");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View();
        }

        //-------------------------------------------------------------//
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("UserList");

        }



        //-------------------------------------------------------------//
        [BindProperty]
        public List<string> Roles { get; set; }
        [BindProperty]
        public IdentityUser CurentUser { get; set; }
        public List<IdentityRole> AllRoles { get; set; }
        public List<string> UserRoles { get; set; }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ManageUserRole(string id)
        {

            CurentUser = await _userManager.FindByIdAsync(id);

            //if (CurentUser == null)
            //{
            //    // Handle the case where the user is not found.
            //    return NotFound();
            //}

            UserRoles = (await _userManager.GetRolesAsync(CurentUser)).ToList();
            AllRoles = _roleManager.Roles.ToList();
            ViewBag.Roles = CurentUser;
            ViewBag.ID = id;
            ViewBag.AllRoles = AllRoles;
            var roleInfo = new 
            {
                Roles = UserRoles,
                ID = id,
                UserName = CurentUser,
                AllRole = AllRoles
            };

            return View(roleInfo);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> PostUserRole(string id)
        {
            CurentUser = await _userManager.FindByIdAsync(id);
            AllRoles = _roleManager.Roles.ToList();

            foreach (var item in AllRoles)
            {
                if (Roles.Contains(item.Name))
                {
                    if (!(await _userManager.IsInRoleAsync(CurentUser, item.Name)))
                    {
                        await _userManager.AddToRoleAsync(CurentUser, item.Name);
                    }
                }
                else
                {
                    if (await _userManager.IsInRoleAsync(CurentUser, item.Name))
                    {
                        await _userManager.RemoveFromRoleAsync(CurentUser, item.Name);
                    }
                }
            }
            return RedirectToAction("UserList");

        }


    }





    
}

Source/Presentation/Management.EndPoint.MVCApp/Controllers/AuthenticationIdentityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BootCampManagement.EndPoint.MVCApp.Controllers
{
    public class AuthenticationIdentityController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        [BindProperty]
        public string UserName { get; set; }
        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public string? ReturnUrl { get; set; }

        public AuthenticationIdentityController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public IActionResult LogIN()
        {
            return View();
        }
        public async Task<IActionResult> PostLogIN()
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(UserName, Password, false, false);
                if (result.Succeeded)
                {
                    return Redirect(ReturnUrl ?? "/");
                }
                else
                {
                  ModelState.AddModelError("", "Invalid user name or password");
                }
            }
            return RedirectToAction("LogIN");
        }

        //-----------------------------------------------------------------------//

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return Redirect("/");
        }

        //----------------------------------------------------------------------//

        public async Task<IActionResult> AccessDenied() { 
        
        return View();
        }


    }
}

Source/Presentation/Management.EndPoint.MVCApp/Controllers/HomeController.cs
using Main.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Main.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Source/Presentation/Management.EndPoint.MVCApp/Views/Home/Index.cshtml
@{
}

<div class="d-flex flex-column justify-content-center align-content-center">
    @if (User.Identity.IsAuthenticated)
    {
       
        <div class="d-flex flex-row justify-content-center align-content-center mt-5">
            <h1>سلام @User.Identity.Name</h1>
        </div>

    }
    else
    {
        <div class="d-flex flex-row justify-content-center align-content-center mt-5 gap-5 ">
            <a href="/AuthenticationIdentity/LogIN" class="btn btn-danger">Log In</a>
            <a href="/AccountIdentity/CreateUser" class="btn btn-success">Create Account</a>
        </div>
        <div class="d-flex flex-row justify-content-center align-content-center mt-5">
            <h1>مشخصات برای لاگین</h1>
        </div>
        <div class="d-flex flex-row justify-content-center align-content-center mt-5">
           <table class="table table-bordered table-striped">
                <tr>
                    <td>Number</td>
                    <td>UserName</td>
                    <td>Passdword</td>
                    <td>Role</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Ali</td>
                    <td>Ali123#</td>
                    <td>Admin</td>
                </tr>
                 <tr>
                    <td>2</td>
                    <td>Hossein</td>
                    <td>Hossain123#</td>
                    <td>User</td>
                </tr>
           </table>
            
        </div>
        

    }
</div>



















@* <button type="submit" asp-action="LogIN" asp-controller="AuthenticationIdentity">
    LogIn
</button>
<button type="submit" asp-action="CreateUser" asp-controller="AccountIdentity">
    Create Acc *@
@* <div class="d-flex align-items-center justify-content-center" style="height: 90vh">
    <div class="rounded border border-primary d-inline-flex align-items-center justify-content-center" style="width: 350px; height: 400px">
        <form id="genderForm" >
            <div class="mb-3">
                <label for="exampleInputCode" class="form-label">Code</label>
                <input type="number" min="1" max="1000" class="form-control" id="exampleInputCode" name="Code" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="InputEn" class="form-label">TitleEn</label>
                <input type="text" class="form-control" id="InputEn" name="TitleEn">
            </div>
            <div class="mb-3">
                <label for="InputFa" class="form-label">TitleFa</label>
                <input type="text" class="form-control" id="InputFa" name="TitleFa">
            </div>
            <button type="button" class="btn btn-primary" onclick="submitForm()">Submit</button>
        </form>
    </div>
</div>
<script>
    function submitForm() {
        var formData = {
            Code: $('#exampleInputCode').val(),
            TitleEn: $('#InputEn').val(),
            TitleFa: $('#InputFa').val()
        };

        $.ajax({
            url: '/Gender/Create', 
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(formData),
            success: function (result) {
                console.log('Data submitted successfully:', result);
            },
            error: function (error) {
                console.error('Error submitting data:', error);
            }
        });
    }
</script> *@