Source/Presentation/Management.EndPoint.MVCApp/Controllers/TransactionTypeController.cs
using Application.Schema.HR;
using Domain.Concrete.Schema.HR;
using Main.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NHibernate.Linq;


namespace BootCampManagement.EndPoint.MVCApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TransactionTypeController : Controller
    {
        private readonly TransactionTypeRepository _transactionTypeRepository;
        private readonly NHibernate.ISession _session;
        public TransactionTypeController(NHibernate.ISession session, TransactionTypeRepository transactionTypeRepository)
        {
            _transactionTypeRepository = transactionTypeRepository;
            _session = session;
        }

        public IActionResult Index()
        {
            var transactionTypes = _transactionTypeRepository.TransactionTypes.ToList();
            return Json(transactionTypes);
        }

        public IActionResult TransactionTypeList()
        {
            var transactionTypes = _transactionTypeRepository.TransactionTypes.ToList();
            return View(transactionTypes);
        }

        
        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                _transactionTypeRepository.BeginTransaction();

                var person = await _transactionTypeRepository.TransactionTypes.FirstOrDefaultAsync(x => x.Code == id);

                if (person == null)
                    return BadRequest("چنین چیزی وجود ندارد.");

                await _transactionTypeRepository.Delete(person);
                await _transactionTypeRepository.Commit();

                return Json(new { success = true, message = " با موفقیت حذف شد." });
            }
            catch (Exception ex)
            {
                await _transactionTypeRepository.Rollback();
                return Json(new { success = false, message = $"خطا در حذف : {ex.Message}" });
            }
            finally
            {
                _transactionTypeRepository.CloseTransaction();
            }
        }
        private async Task SaveAsync(TransactionType traType)
        {
            await _session.SaveOrUpdateAsync(traType);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] TransactionType traType)
        {
            try
            {
                //await SaveAsync(traType);
                _transactionTypeRepository.BeginTransaction();
                await _transactionTypeRepository.Save(traType);
                await _transactionTypeRepository.Commit();

                return Ok(new { Message = "اطلاعات با موفقیت ذخیره شد." });
            }
            catch (Exception ex)
            {
                return BadRequest(new { Message = $"خطا در ذخیره اطلاعات: {ex.Message}" });
            }
        }
        public IActionResult CreateType()
        {
            return View();
        }
    }
}

Source/Presentation/Management.EndPoint.MVCApp/Views/TransactionType/CreateType.cshtml
@model Domain.Concrete.Schema.HR.TransactionType

@{
    ViewData["Title"] = "CreateType";
}
<h2>CreateType</h2>

<form method="post" asp-controller="TransactionType" asp-action="Create" onsubmit="submitForm(); return false;">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label asp-for="Code">Code:</label>
        <input type="number" asp-for="Code" class="form-control" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="TitleEn">TitleEn:</label>
        <textarea asp-for="TitleEn" class="form-control"></textarea>
        <span asp-validation-for="TitleEn" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TitleFa">TitleFa:</label>
        <textarea asp-for="TitleFa" class="form-control"></textarea>
        <span asp-validation-for="TitleFa" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary mt-5">Save</button>
</form>


<script>
    function submitForm() {
        const form = document.querySelector('form');
        const formData = new FormData(form);
        const jsonData = JSON.stringify(Object.fromEntries(formData));

        fetch('/TransactionType/Create', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: jsonData
        })
            .then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Network response was not ok.');
                    alert('.شکست عملیات . مقادیر را بررسی کنید')

                }
            })
            .then(data => {
                alert('اطلاعات با موفقیت ثبت شد');
                window.location.href = '/TransactionType/TransactionTypeList'
            })
            .catch(error => {
                console.error('Error:', error);
                alert('.شکست عملیات . مقادیر را بررسی کنید')

            });
    }
</script>

Source/Presentation/Management.EndPoint.MVCApp/Views/TransactionType/TransactionTypeList.cshtml
@{
}
@* @model Domain.Concrete.Schema.HR.TransactionType
 *@
<div class="d-flex align-items-start justify-content-center" style="height: 50vh">
    <table class="table" style="width: 1000px " dir="rtl">
        <thead>
            <tr>
                <td scope="col">Code</td>
                <th scope="col">TitleEn</th>
                <th scope="col">TitleFa</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var TT in Model)
            {

                <tr>
                    <td>@TT.Code</td>
                    <td>@TT.TitleEn</td>
                    <td>@TT.TitleFa</td>
                    <td>
                       <button type="button" asp-page="" class="btn btn-danger" onclick="deleteGender(@TT.Code) ">حذف</button>
                        @* <button type="button" asp-action="Delete" asp-controller="TransactionTypeController"  class="btn btn-danger"  >حذف</button> *@

                    </td>
                </tr>
            }

            
        </tbody>
    </table>
</div>

<script>
    function deleteGender(Code) {
        console.log(Code)
        if (confirm("آیا از حذف این  مطمئن هستید؟")) {
            fetch(`/TransactionType/Delete/${Code}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                },
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('حذف موفق');
                        location.reload();
                    } else {
                        alert('شکست در حذف');
                    }
                })
                .catch((error) => {
                    alert('شکست در حذف');
                    console.error('Error:', error);
                });
        }
    }

</script>